### ISSUE TITLE
getTransactions limited by txType ?  also mandatory parameters that shouldn't be mandatory?

### ISSUE THREAD

**Issue by omniwolf** [davesag/ir-api#770]
Hello,
I know this is an old possibly unmaintained repository, but I'm trying to use it in my Node.JS app and found something strange
In the /api/getTransactions.js file it has this:

```javascript
txTypes: ['isRequired', isArrayOf(['Brokerage', 'Trade''])],
``` 

So it seems we can only request Brokerage and Trade transaction types?  I want "Withdrawal".   If I add it there it works, but I guess would be nice to allow all transaction types out of the box?

I also see that txType is `IsRequired`, as well as fromTimestampUtc and toTimestampUtc.  None of these are actually required in the IR API, so seems odd that you would force it.

**Comment by omniwolf** [comment]
Made a PR with the fixes for this.
https://github.com/davesag/ir-api/pull/772

**Comment by davesag** [comment]
thanks for the contributions - sorry it took so long to get to
